# Generated by Django 5.2.2 on 2025-06-12 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='movies/', verbose_name='Изображение')),
                ('year', models.IntegerField(verbose_name='Год выпуска')),
                ('rating', models.FloatField(verbose_name='Рейтинг(0-10)')),
            ],
        ),
    ]
